#Categories for different recivers
categories = {
    "Food":[
        "SYSTEMBOLAGET",
        "Delivery Hero Sweden",
        "MAXI ICA STORMARKNAD",
        "FOODORA AB",
        "HEMKÖP STOCKHOLM HOR",
        "IZ \*OH POKE GROUP",
        "PONG LINDHAGEN",
        "Wolt",
        "MATHEM SE",
        "COOP NÄRA REIMERSHOL",
        "PRIMOCIAOCIAO H",
        "TASTORY LINDH",
        "WWW.DINEIN.NU",
        "Klarna \*mathem",
        "COOP NARA REIMERSHOL",
        "105 FABRIQUE HORNSTU",
        "COOP REIMERSHOL"
        "112 FABRIQUE FRIDHEM",
        "LILYS HORNSBERG STRA",
        "ICA KVANTUM LILJEHOL",
        "IZ \*BROD   SALT BA",
        "ESPRESSO HOUSE 371",
        "INDIAN INN",
        "CITY WOK",
        "WWW CONVINI SE",
        "COOP REIMERSHOL",
        "FABRIQUE FRIDHEM",
        "7 ELEVEN",
        "IZ \*O M CAFE CAMIN",
        "CO 229",
        "IZ \*TEKLE 18122 AB"],
    "Shopping":[
        "Esprit Online Shop",
        "INTERSPORT STOC",
        "Stadium Sweden Aktie",
        "WEBHALLEN",
        "CLASOHLSON COM SE",
        "CDON SE",
        "Björn Borg Retail AB",
        "CERVERA LILJEHOLMEN",
        "ELLOS SE",
        "LJUSHUSET",
        "KOMPLETT SE",
        "KJELL O CO 91",
        "DRAGONS LAIR",
        "PLANTAGEN KUNGE",
        "SPECSAVERS SE",
        "Elgiganten se",
        "Inet AB",
        "Smartphoto group NV",
        "DELL PRODUCTS",
        "KJELL O CO 50",
        "ELGIGANTEN STHL"],
    "Services":[
        "GOOGLE \*Stadia",
        "Autogiro DAGENS NYHET",
        "NETFLIX COM",
        "Telia Sverige",
        "GOOGLE \*Google Stora",
        "Knivbrev",
        "RATSIT SE",
        "Patreon\* Membership",
        "IF SKADEFÖRS",
        "GOOGLE \*YouTube Vide",
        "Spotify",
        "HBO Nordic AB",
        "DRI\*NVIDIA Store",
        "WWW WELLNET SE",
        "SKEPTOID ORG",
        "GOOGLE\*STADIA",
        "K\*Interflora",
        "GOOGLE\*GOOGLE STORAG"],
    "Entertainment":[
        "SF Anytime AB",
        "EA \*ORIGIN COM",
        "EA \*ELECTRONIC ARTS"],
    "Transport":[
        "APP SL BILJETT",
        "Swish betalning AB STORSTOCKHOLMS L",
        "E HANDEL SL SE",
        "M SWEDEN",
        "BETALA P",
        "UberSE_PBV"],
    "Home":[
        "IKEA KUNGENS KURVA",
        "BORJES FERG",
        "BSH HOME APPLIANCES",
        "COLORAMA TROLLBECKEN",
        "STALANDS ASOGATAN",
        "ELEKTROSKANDIA SVERI",
        "HSB Stockholm",
        "REIMERS BÅTSÄ",
        "Omsättning lån",
        "Ownit / Bill",
        "Vardagspaket Månadspris kort",
        "Sveriges Inge"],
    "Transfer":[
        "Överföring",
        "SWISH",
        "Lön",
        "Betalning BG 5299-9869 ICA BANKEN A",
        "BROMMA EXPRE",
        "Swish",
        "GOD JUL!",
        "Patrik Hemkonto 911216-1188",
        "AVANZA",
        "Bankgiroinsättning"]
    }